on:
  push:
    branches:
      - master
    paths:
      - 'deployment/*'
      - '.github/workflows/configure-azure.yml'

name: ConfigureContosoOnAzure

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/actions/login@master
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run: |
        az webapp list --query "[?state=='Running']"
