on:
  push:
    branches:
      - master
    paths:
      - 'deployment/*'
      - '.github/workflows/configure-azure.yml'

name: provision-contoso-env

jobs:
  deploy-arm-template:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/actions/login@master
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run: |
        ls
        ls deployment

    - run: |
        az group deployment create --resource-group 'mySampleRG' --template-file deployment/azuredeploy.json --parameters p_site_prefix=davepfx1234
