on:
  push:
    branches:
      - master
    paths:
      - 'deployment/*'
      - '.github/workflows/configure-azure.yml'

name: provision-contoso-env

jobs:
  prepare-environment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      
    - uses: azure/actions/login@master
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

  create-resource-group:
    needs: prepare-environment
    runs-on: ubuntu-latest
    steps:
    - run: |
        az group create --name 'mySampleRG' --location 'westus'

  deploy-arm-template:
    needs: prepare-environment
    runs-on: ubuntu-latest
    steps:
    - run: |
        az group deployment create --resource-group 'mySampleRG' --template-file deployment/azuredeploy.json --parameters @deployment/azuredeploy.parameters.json --parameters p_site_prefix=davepfx1234
