name: Node.js Package

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.16.3
      - run: npm install jest
      - run: npm install jest-junit-reporter
      - run: npm run unit-test

#  deploy-app:
#    runs-on: ubuntu-latest
#    needs: build-test
#    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.16.3
      - uses: azure/actions/login@master
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v1
        with: 
          app-name: davepfx1234-web-dev
          #publish-profile: ${{ secrets.azureWebAppPublishProfile }} # Define secret variable in repository settings as per action documentation
          #package: '.'  #default value is entire repo
          # If your function app project is not located in your repository's root
          # Please consider prefixing the project path in this package parameter

#  publish-gpr:
#    needs: build-test-publish
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - uses: actions/setup-node@v1
#        with:
#          node-version: 10.16.3
#          registry-url: https://npm.pkg.github.com/
#          scope: '@dmckinstry'
#      - run: npm publish
#        env:
#          NODE_AUTH_TOKEN: ${{secrets.GPR_PAT}}
#          GITHUB_TOKEN: ${{secrets.GPR_PAT}}
