on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Say Hello - gerwaldo Demo
    steps:
    # To use this repository's private action, you must check out the repository
    - name: Checkout
      uses: actions/checkout@v1
    - uses: ./ # Uses an action in the root directory
    - name: Hello world action step
      id: hello
      uses: gerwaldo/ContosoAir/.github/workflows@v1
      with:
        who-to-greet: 'Hello gerwaldo, Demo @ Azure Baseline Event'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
