name: Node.js Package

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.16.3
      - run: npm install jest
      - run: npm install jest-junit-reporter
      - run: npm run unit-test

  publish-gpr:
    needs: build-test-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.16.3
          registry-url: https://npm.pkg.github.com/
          scope: '@dmckinstry'
#      - run: npm publish
#        env:
#          NODE_AUTH_TOKEN: ${{secrets.GPR_PAT}}
#          GITHUB_TOKEN: ${{secrets.GPR_PAT}}
